<section class="company__content">
    <style>
        .contact-info-btn {
            margin-left: 10px;
        }
        @media (max-width: 640px) {
            .contact-info-btn {
                margin-left: 0;
                margin-bottom: 20px;
                width: 100%;
            }

            .contact-btn__container {
                flex-direction: column;
            }
        }
    </style>
    <h2><?php echo $block->escapeHtml($block->getWelcomeText()) ?></h2>
    <h3>
        Контакт-центр працює для Вас щоденно з 07:30 до 22:30.

    </h3>
    <address>
        <ul>
            <li>
                <b>
                    <a href="tel:0800202727">0 800 20 27 27</a>
                </b>
                <span>
Дзвінки зі стаціонарних телефонів, а також мобільних операторів Київстар, Vodafone і lifecell
безкоштовно по всій Україні.
</span>
            </li>
            <li>
                <b>
                    <a href="tel:0442329027">044 232 90 27</a>
                </b>
                <span>
Дзвінки тарифікуються згідно з тарифами Вашого оператора.
</span>
            </li>
            <li>
                <b>
                    <a href="tel:0931704727">093 170 47 27</a>
                </b>
                <span>
Дзвінки тарифікуються згідно з тарифами Вашого оператора.
</span>
            </li>
            <li>
                <b>
                    <a href="mailto:info@on.epicentrk.ua">info@on.epicentrk.ua</a>
                </b>
                <span>
Електронна пошта для Ваших пропозицій, скарг та заяв.
</span>
            </li>
            <li>
                <b>
                    <a href="mailto:beznal@on.epicentrk.ua">beznal@on.epicentrk.ua</a>
                </b>
                <span>
Електронна пошта для корпоративних клієнтів, запит на отримання
рахунків.
</span>
            </li>
            <li>
                <b>
                    <a href="mailto:apteka@epicentrk.ua">apteka@epicentrk.ua</a>
                </b>
                <span>
Електронна пошта для замовлень ліків.
</span>
            </li>
            <li>
                <b>
                    <a href="/info/garanty/">Гарантія та сервіс</a>
                </b>
                <span>
Отримання інформації щодо сервісного обслуговування та
повернення товару.
</span>
            </li>
            <li> <span>
<b> <a href="/ua/info/spivpracya/">Контакти центрального офісу</a> </b></span></li>
        </ul>
        <br>
    </address>
</section>
